apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::036292124076:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12G2LEPG2OCIY
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-18T10:36:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1495"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 1f46a8ad-43df-4862-9fac-7894263b7727
