apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::036292124076:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KJIKD5BBIEUA
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-17T19:18:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1869"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 65edf9c1-d41a-4a37-b0e7-35120653b7f6
