apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::036292124076:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-19JWX7CDBHHDS
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-18T14:58:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1762"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 14fcd007-cdaa-46d8-88d3-cfc34f83d881
